#!/bin/sh
#
# ownightly - test openwbem
#
# 

unset OWLONGTEST

set -a
set -x
set -u

TESTDIR=/usr/local/build/owtemp
LOGFILE=$TESTDIR/log.txt
MAILTO="dnuffer@vintela.com"

##############################################################################
doTest()
{
	cd $TESTDIR/openwbem20
	CONFIGOPTS="--enable-debug-mode"

	./cvsbootstrap.sh > $LOGFILE 2>&1
	./configure $CONFIGOPTS >> $LOGFILE 2>&1
	if [ "$OSTYPE" = "linux-gnu" ]; then
		killall -9 owcimomd
	fi
	make -j3 >> $LOGFILE 2>&1 \
		&& make -j3 check >> $LOGFILE 2>&1 \
		&& OWLONGTEST=1 make -j3 check >> $LOGFILE 2>&1 \
		&& make clean >> $LOGFILE 2>&1 \
		&& make -j3 distcheck >> $LOGFILE 2>&1

	RVAL=$?

	if [ "$RVAL" = "0" ]; then 
		# now try with optimizations
		CONFIGOPTS=""
		./cvsbootstrap.sh > $LOGFILE 2>&1
		./configure $CONFIGOPTS >> $LOGFILE 2>&1
		if [ "$OSTYPE" = "linux-gnu" ]; then
			killall -9 owcimomd
		fi
		make -j3 >> $LOGFILE 2>&1 \
			&& make -j3 check >> $LOGFILE 2>&1 \
			&& OWLONGTEST=1 make -j3 check >> $LOGFILE 2>&1 \
			&& make clean >> $LOGFILE 2>&1 \
			&& make -j3 distcheck >> $LOGFILE 2>&1

		RVAL=$?
	fi

	if [ "$RVAL" = "0" ]; then 
		BUILDRESULT="Success"
	else
		BUILDRESULT="Fail"
		echo "" >> $LOGFILE
	fi


	tail -50 $LOGFILE | mail -s \
		"OpenWBEM nightly distcheck: $BUILDRESULT ($OSTYPE)" $MAILTO
}

##############################################################################

## MAIN ######################################################################

rm -rf $TESTDIR
mkdir $TESTDIR
cd $TESTDIR
cvs -z3 -d :ext:nuffer@cvs.openwbem.sourceforge.net:/cvsroot/openwbem co openwbem20


doTest

