// ===================================================================
// Title:       Master MOF
// Filename:    CIM_Schema25.mof
// Version:     2.5
// Release:     0
// Date:        1/11/2001
// Description: This is overall Schema 
// ===================================================================
// Author     : DMTF Technical Committee
// ===================================================================
// Copyright "2001" Distributed Management Task Force, Inc. (DMTF).
// All rights reserved.  
// DMTF is a not-for-profit association of industry members dedicated 
// to promoting enterprise and systems management and interoperability. 
// DMTF specifications and documents may be reproduced for uses
// consistent with this purpose by members and non-members, 
// provided that correct attribution is given. 
// As DMTF specifications may be revised from time to time, 
// the particular version and release cited should always be noted.
// ===================================================================
// includes
// ===================================================================
#pragma include ("CIM_Core25.mof")
#pragma include ("CIM_Events25.mof")
#pragma include ("CIM_User25.mof")
#pragma include ("CIM_Policy25.mof")
#pragma include ("CIM_Application25.mof")
#pragma include ("CIM_System25.mof")
#pragma include ("CIM_Device25.mof")
#pragma include ("CIM_Physical25.mof")
#pragma include ("CIM_Network25.mof")
#pragma include ("CIM_Metrics25.mof")
#pragma include ("CIM_Support25.mof")





