
class EXP_BartComputerSystem : CIM_ComputerSystem
{
  [ provider("c++::methodtest") ]
   string GetState(
		[in] string s,
		[in] uint8 uint8array[],
		[in(false), out] boolean b,
		[in(false), out] real64 r64,
		[in, out] sint16 io16,
		[in(false), out] string msg,
		[in, out] CIM_ComputerSystem REF paths[],
		[in, out] datetime nullParam);

  [ provider("c++::methodtest") ]
   string ToggleState();

  [ provider("c++::methodtest") ]
   string SetState(
	[IN] string newState);
};

instance of EXP_BartComputerSystem
{
    CreationClassName = "EXP_BartComputerSystem";
    Name = "test";
};

