###############################################################################
# owcimomd configuration file
# Note:
#  All lines that start with a '#' or a ';' character are ignored.
#
#  All of the options in this file are read by owcimomd at start up. The file
#  will only be re-read on restart when a SIGHUP is received.
#  The options that are prefixed with "owcimomd." are meant specifically for 
#  owcimomd.
#  Other options are prefixed with an identifier of the component that is
#  specifically interested in the options. For example the
#  "cppprovifc.prov_location" option is meant specifically for the C++ provider
#  interface. This option is read from the config file by owcimomd and
#  made available to the C++ provider interface upon request.
###############################################################################

################################################################################
# If owcimomd.allow_anonymous is set to true anonymous logins are allowed by
# owcimomd, authentication is disabled and no user name or password is required.
# The default is false
;owcimomd.allow_anonymous = false

################################################################################
# owcimomd.log_location specifies the location of the log file that is
# generated by owcimomd. If this option is set to syslog, owcimomd will log
# all messages through the syslog interface (Recommended). If this option
# is set to null, logging will be disabled completely.  If this option
# is set to anything else, it is assumed it is an absolute path to a file
# that owcimomd will write its log messages to. 
# The default is syslog
;owcimomd.log_location = syslog

################################################################################
# The owcimomd.log_level option specifies the level of logging. This can be
# any one of the following:
#   "debug"    - All debug, info, error and fatalerror messages are logged
#   "info"     - All info, error and fatalerror messages are logged
#   "error"    - All error and fatalerror messages are logged. This is the default.
#   "fatalerror" - Only fatalerror messages are logged.
;owcimomd.log_level = error

################################################################################
# owcimomd.wql_lib specifies the location where the wql processor library
# will be loaded from.
# To disable WQL, either set this option to empty or comment it out.
# The default is "@libdir@/libowwql.@lib_ext@"
owcimomd.wql_lib = @libdir@/libowwql.@lib_ext@

################################################################################
# The owcimomd.dump_socket_io defines the directory where owcimomd will
# dump all socket i/o to log files.  This is usefull for debugging HTTP
# operations and XML.  The files will be called <dir>/owSockDumpIn and
# <dir>/owSockDumpOut.  If this option is not set, or has an empty value,
# dump files will not be used.  Warning: if this option is defined,
# CIM operattions could take twice as long!
;owcimomd.dump_socket_io = /tmp

################################################################################
# The owcimomd.debugflag specifies whether or not owcimomd will run in
# debug mode. If this option is true, owcimomd will not detache from the
# terminal and will send all logging to the terminal. While in this mode
# owcimomd can be properly terminated by simply hitting Ctrl-C or sending it
# a SIGTERM signal (SIGTERM also works if owcimomd.debugflag is false)
# Also using the command line parameter -d turns on debug mode.
;owcimomd.debugflag = false

################################################################################
# The authentication module to be used by owcimomd.  This should be a
# an absolute path to the shared library containing the authentication module.
owcimomd.authentication_module = @libdir@/openwbem/authentication/libpamauthentication.@lib_ext@

################################################################################
# The maximum number of classes that will be cached by the cimom.
# The default is 128
;owcimomd.max_class_cache_size = 128

################################################################################
# A space delimited list of system users who are allowed to access the CIMOM.
# This option is only enforced by the pam authentication module, and has no
# effect if you are not using http Basic authentication together with the
# pam authentication module.
# Set this value to * to allow all users to authenticate (for instance, if 
# you choose to control access with ACLs instead). 
# This option is DEPRICATED.  Use owcimomd.allowed_users instead.
pam.allowed_users = *

################################################################################
# A space delimited list of system users who are allowed to acces the CIMOM
# The special value * to allow all users to authenticate (for instance, if 
# you choose to control access with ACLs instead). 
# This option is enforced for all authentication methods. If 
# owcimomd.allow_anonymous = true, it is not enforced.
# The default is *
owcimomd.allowed_users = root

################################################################################
# If the simple authentication module is used, this needs to be the path to
# the password file
simple_auth.password_file = @sysconfdir@/openwbem/simple_auth.passwd

################################################################################
# When this variable is set to true, the cimom will not attempt to
# deliver indications.  
# The default is false
;owcimomd.disable_indications = false

################################################################################
# owcimomd.ACL_superuser specifies the user name of the user that has access to
# all CIM data in all namespaces maintained by the CIMOM. This user can be used
# to administer the /root/security namespace which is where all ACL user rights
# are stored. ACL processing is not enabled until the OpenWBEM_Acl1.0.mof file
# has been imported.
;owcimomd.ACL_superuser =

################################################################################
# owcimomd.request_handler_TTL specifies how many minutes the request
# handlers will stay loaded after they are accessed.  If the value of this
# option is -1, the request handlers will never be unloaded.  
# The default is 5
;owcimomd.request_handler_TTL = 5

################################################################################
# owcimomd.check_referential_integrity specifies whether the CIM Repository
# will perform extra checks to help ensure referential integrity between
# associations and propagated keys.  Since these checks can add overhead,
# it is recommended to enable this option during development and debugging
# and disable it in production if the overhead is too expensive.
# The default is false
;owcimomd.check_referential_integrity = false

################################################################################
# owcimomd.polling_manager_max_threads specifies the maximum number of 
# concurrent threads that will be allowed to run by the polling manager.
# This should only be a concern if the cimom has a lot of polled providers.
# The default is 256
;owcimomd.polling_manager_max_threads = 256

################################################################################
# owcimomd.max_indication_export_threads specifies the maximum number of 
# concurrent threads to export indications that will be allowed to run by the 
# indication server.
# This may need to be increased if a lot of indications are being exported.
# The default is 30
;owcimomd.max_indication_export_threads = 30

################################################################################
# owcimomd.restart_on_error controls the use of the fatal signal handler.
# If this option is set to true, if owcimomd receives a fatal signal
# (SIGSEGV, SIGBUS, SIGILL, SIGFPE or SIGABRT) which may be caused by faulty
# code, then it will restart itself.  Note that this feature is disabled if
# the cimom is built in debug mode (OW_DEBUG is defined).
# This feature helps to keep the cimom running in the case a buggy provider
# (or the cimom itself) causes a fatal signal.
# The default is true
;owcimomd.restart_on_error = true

################################################################################
# owcimomd.authorization_lib specifies the location the authorization
# library will be loaded from.
# This is DEPRICATED.  Use owcimomd.authorization2_lib instead.  This 
# remains for backwards compatibility. 
;owcimomd.authorization_lib = @libdir@/openwbem/libowsimpleauthorizer.@lib_ext@

################################################################################
# owcimomd.authorization2_lib specifies the location the authorization
# library will be loaded from.
# If this option is empty or commented out, no authorization module will be
# used.
owcimomd.authorization2_lib = @libdir@/openwbem/libowsimpleauthorizer2.@lib_ext@

################################################################################
# owcimomd.interop_schema_namespace specifies the namespace which contains the
# CIM Interop schema. 
# The default is root
;owcimomd.interop_schema_namespace = root

################################################################################
# cppprovifc.prov_TTL specifies how many minutes the C++ provider manager
# will keep a provider in memory.  If a provider has not been accessed for
# longer than this value, it will be unloaded and the memory associated with
# it will be freed.  If the value of this option is -1, the providers will
# never be unloaded.  
# The default is 5
;cppprovifc.prov_TTL = 5

################################################################################
# The remote provider interface uses a connection pool to re-use remote 
# connections. remoteprovifc.max_connections_per_url specifies the maximum
# number of connections per url that will be pooled.  The value must be a
# non-negative integer.  
# The default is 5
;remoteprovifc.max_connections_per_url = 5

################################################################################
# If OpenWBEM is built with zlib, it can use deflate compression in the HTTP
# responses.  This option controls whether it will acutally use it or not.
# The default is true
;http_server.enable_deflate = true

################################################################################
# http_server.listen_addresses option specifies the local addresses to listen
# on.  The option is a space delimited list.  Each item is either a hostname
# or an IP address.  The value 0.0.0.0 means to listen on all local addresses.
# The default is 0.0.0.0
;http_server.listen_addresses = 0.0.0.0

################################################################################
# http_server.http_port option specifies the port number owcimomd will listen
# on for all HTTP communications.
# Set this to -1 if you do not want to support HTTP connections (for
# instance, you only want to support HTTPS connections).  If a value of 0
# is given, a port will be dynamically assigned at run-time.
# The default is 5988
;http_server.http_port = 5988

################################################################################
# http_server.https_port specifies the port number owcimomd will listen on
# for all HTTPS communications.
# Set this to -1 if you do not want to support HTTPS connections.
# If a value of 0 is given, a port will be dynamically assigned at run-time.
# The default is 5989
;http_server.https_port = 5989

################################################################################
# http_server.max_connections specifies the maximum number of concurrent
# connections owcimomd will handle.
# The default is 30
;http_server.max_connections = 30

################################################################################
# http_server.SSL_cert specifies the location of the file that contains the
# host's private key and certificate that will be used by Open SSL for HTTPS
# communications. 
# The default is @sysconfdir@/openwbem/hostkey+cert.pem
http_server.SSL_cert = @sysconfdir@/openwbem/hostkey+cert.pem

################################################################################
# Tell the http server to use Digest authentication
# Digest will bypass the Basic authentication mechanism.  
# You must set up the digest password file using owdigestgenpass to use digest.
# Digest doesn't use the authentication module specified by the 
# owcimomd.authentication_module config item.
# If this option is true, then Basic will not be used.
# If this option is false, then Basic will be used.
# The default is true
http_server.use_digest = false

################################################################################
# If the Digest authentication option is enabled, this needs to be the path to
# the password file.
http_server.digest_password_file = @sysconfdir@/openwbem/digest_auth.passwd

################################################################################
# Tell the http server to allow local authentication
# local authentication allows a local system user to authenticate without
# supplying a password, instead relying on filesystem permissions.  This can
# be enabled in conjunction with either http Basic or Digest.
# The default is false
;http_server.allow_local_authentication = false

################################################################################
# http_server.single_thread specifies whether or not owcimomd process connection
# in a separate thread or in the same thread as the server. This option is
# really only for debug purposes and should not be of any use to the
# typical user. 
# The default is false
;http_server.single_thread = false

################################################################################
# http_server.use_UDS specifies whether the http server will listen on a
# Unix Domain Socket.  
# The default is true
;http_server.use_UDS = true

################################################################################
# http_server.reuse_addr specifies whether the http server will set the 
# SO_REUSEADDR flag when it listens on a socket.  This is provided because some
# Unix kernels have security problems when this option is set.
# If this option is not turned on, you may not be able to immediately restart
# the daemon because it can't listen on the port until the kernel releases it.
# It's OK to use on current linux versions.  Definitely not on
# OLD (kernel < 1.3.60) ones. 
# See http://monkey.org/openbsd/archive/misc/9601/msg00031.html
# or just google for "bind() Security Problems"
# If you specify interfaces to listen on other than 0.0.0.0 using the 
# http_server.listen_addresses option, then there is no security problem with
# enabling this option.
# The default is true
;http_server.reuse_addr = true

################################################################################
# http_server.timeout specifies the number of seconds that the server will use
# as a timeout when communicting with clients. The value must be > 0.
# The default is 300 (5 minutes).
;http_server.timeout = 300;

################################################################################
# http.default_content_language specified the default content-laguage that
# will be returned to an HTTP client when the accept-language header was used
# on the request and a provider has not explicity set the content-language.
# The default is en
;http_server.default_content_language = en

################################################################################
# slp.enable_advertisement controls whether the slp provider advertises with SLP
# The default is true
;slp.enable_advertisement = true

################################################################################
# The following options will probably not need to be modified.
################################################################################


################################################################################
# owcimomd.services_path Specifies the directory containing the services
# shared libraries to be loaded by the CIMOM.
# You probably don't need to modify this option.
# The default is "@libdir@/openwbem/services"
owcimomd.services_path = @libdir@/openwbem/services

################################################################################
# owcimomd.request_handler_path Specifies the directory containing the
# request handler shared libraries to be loaded by the CIMOM.
# You probably don't need to modify this option.
# The default is "@libdir@/openwbem/requesthandlers"
owcimomd.request_handler_path = @libdir@/openwbem/requesthandlers

################################################################################
# owcimomd.libexecdir specifies the locaction of the libexec directory.
# Binaries that owcimomd relies on are expected to be in this directory.
# You probably don't need to modify this option.
# The default is "@libexecdir@/openwbem"
owcimomd.libexecdir = @libexecdir@/openwbem

################################################################################
# owcimomd.owlibdir specifies the locaction of the lib directory.
# Dynamically loaded libraries that owcimomd relies on are expected to be in
# this directory.
# You probably don't need to modify this option.
# The default is "@libdir@/openwbem"
owcimomd.owlibdir = @libdir@/openwbem

################################################################################
# owcimomd.datadir specifies the directory where owcimomd will place its data
# file (repositories). 
# You probably don't need to modify this option.
# The default is "@localstatedir@/openwbem"
owcimomd.datadir = @localstatedir@/openwbem

################################################################################
# owcimomd.provider_ifc_libs specifies the location where all the provider
# interfaces will be loaded from. owcimomd assumes all shared libraries in
# this directory are provider interfaces. If a shared library in this directory
# does not support the provider interface api, it will be rejected. 
# You probably don't need to modify this option.
# The default is "@libdir@/openwbem/provifcs"
owcimomd.provider_ifc_libs = @libdir@/openwbem/provifcs

################################################################################
# One of the provider interfaces provided with owcimomd is the C++ provider
# interface. The cppprovifc.prov_location option specifies where the C++
# provider interface will load it's providers from.  Multiple directories
# can be specified, separated by ':' or ';'.  
# You probably don't need to modify this option.
# The default is "@libdir@/openwbem/c++providers"
cppprovifc.prov_location = @libdir@/openwbem/c++providers

################################################################################
# http_server.uds_filename specifies the name of the unix domain socket the
# http server will listen on.
# You probably don't need to modify this option.
# The default is /tmp/OW@LCL@APIIPC_72859_Xq47Bf_P9r761-5_J-7_Q@PACKAGE_PREFIX@
;http_server.uds_filename = /tmp/OW@LCL@APIIPC_72859_Xq47Bf_P9r761-5_J-7_Q@PACKAGE_PREFIX@

################################################################################
# One of the provider interfaces provided with owcimomd is the NPI provider
# interface. The npiprovifc.prov_location option specifies where the NPI
# provider interface will load it's providers from. 
# The default is "@libdir@/openwbem/npiproviders"
npiprovifc.prov_location = @libdir@/openwbem/npiproviders

################################################################################
# One of the provider interfaces provided with owcimomd is the CMPI provider
# interface. The cmpiprovifc.prov_location option specifies where the CMPI
# provider interface will load it's providers from. 
# The default is "@libdir@/openwbem/cmpiproviders"
cmpiprovifc.prov_location = @libdir@/openwbem/cmpiproviders

################################################################################
# One of the provider interfaces provided with owcimomd is the perl provider
# interface. The perlprovifc.prov_location option specifies where the perl
# provider interface will load it's providers from. 
# The default is "@libdir@/openwbem/perlproviders"
perlprovifc.prov_location = @libdir@/openwbem/perlproviders


