// ===================================================================
// OpenLinux_OperatingSystem
// ===================================================================
   [Description ("An example")] 
class OpenLinux_OperatingSystem : CIM_OperatingSystem
{
  [Description (
		"The contents of /etc/.installtest"),
		 provider("c++::olver") ]
   string Version;

};

