// ===================================================================
// Title      : Master MOF
// Filename   : CIM_Schema22.mof
// Version    : 2.2
// Date       : 06/01/1999
//     Draft Schema v 2.2 (05/10/1999)
// Author     : DMTF TDC
// Description: 
// ===================================================================
// ===================================================================
// Includes
// ===================================================================
#pragma Include ("CIM_Core22.mof")
#pragma Include ("CIM_Application22.mof")
#pragma Include ("CIM_System22.mof")
#pragma Include ("CIM_Device221.mof")
#pragma Include ("CIM_Physical22.mof")
#pragma Include ("CIM_Network22.mof")
#pragma Include ("CIM_DAP22.mof")



