// ===================================================================
// Test Instance
// ===================================================================
[Description ("Used to test instance provider.") ]
class TestInstance
{
	[Description ("Name"), KEY]
		string Name;
		
	[Description ("String array of bogus values") ]
		string Params[];
};

