#!/bin/sh 

STAGEDIR=`pwd`/stage
#STAGEDIR=$STAGEDIR/`dirname $1`/stage

LD_LIBRARY_PATH=$STAGEDIR/usr/local/lib:$STAGEDIR/usr/local/lib/openwbem/services:$LD_LIBRARY_PATH
# AIX
LIBPATH="$LD_LIBRARY_PATH:$LIBPATH" 

# HP-UX
SHLIB_PATH="$LD_LIBRARY_PATH:$SHLIB_PATH"

# Mac OSX
DYLD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DYLD_LIBRARY_PATH

PATH=$STAGEDIR/usr/local/bin:$PATH

export PATH LD_LIBRARY_PATH


